<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: piet
 * Date: Mon, 23 Dec 2019 10:41:49 +0100
 */

$conf['title'] = 'TutorWiki';
$conf['license'] = 'cc-by-sa';
$conf['maxtoclevel'] = '5';
$conf['maxseclevel'] = '5';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';

// end auto-generated content
